# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# container: maven:3.6.1-jdk-11
container: 'ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    ls -R /_w/
  displayName: 'Run a multi-line script'

- task: ApplicationSecurity@1
  inputs:
    AppSecTestService: 'prod account'
    applications: '2433ac8c-4059-e811-9423-002590ac753d'
    scanname: 'simpleIOTscanTestmaven'
    scantype: 'static'